weights: last_widerface_weights.pt
cfg: ''
data: /content/drive/.shortcut-targets-by-id/1UVNfjZquM-rwkE-dCpS7i2J2HZEiC9ke/20220121_DOANTOTNGHIEP/20220121_Train_face_emoji_tranfer_widerface/yolov5/data/data.yaml
hyp: hyp.yaml
epochs: 100
batch_size: 84
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp
